language: go
go:
- 1.9
script: go vet
before_deploy:
- "./build.sh"
deploy:
  provider: releases
  api_key:
    secure: m1DLJl99yEFv4hUUcNNcje9lLVpKM0hnU+C8qO6lydX/+maiNQHe0nRm1o/YUBEoE10a9mis6hI31qBFxaHKHko70WQDZ0cDLQOEyEIUppC8M0utPWYOLvD4wn5ApKxQGwwMBpTrqM4Sk/CUqeVB+95wRBMqf2xgkqb8YNKMFuioexYWWJ2YiqW3aTIelg18P/0fsegMBUvPEKH8FzESNt8+oDW8ua2PQm4C2MzTUKFOe0ynP5BFOU+ry49n6hVLO1EmUYcc4KXDKt0aiD0YDDEx+0JPHcr+iRqqJ9YrdwAXJ44NjaYlwQoH3h8I4ftHVdcw4/xF2m1p7F0iTzjDC6hW1PKwHqGEa619fnjD6ZJu/eIfXlFRXYX/I7YbYg7ZzpfS3ZBi5me60o/7GShphCNrKfVcUgK4EOjn5iggaZOyVSWanpd8hGaDSJvemtce6tn/iSbXt8vZD59OEbl2XhMl2CNz6btgRMo4pjXm7fFhmsO/XMSMvd/CkX9TsMqwcV3GozRyQ2yPjyAkVuvQ4ffimf1lMJrD0ga5n5r+EJ+HbUoaFy+vHEqzPP1YtNXx5v2cTexPKEDFCtyIN5tFSjiMFtFR8vRAdu6BuBeXk80RE+jMZA+DCuF1JsAYjVW+Rf0xuvf1ghCASygZjhz8h1v5wR8JgNsefpwXIcshazs=
  skip_cleanup: true
  file:
    - release/terraform-provider-kafka-connect-darwin-amd64
    - release/terraform-provider-kafka-connect-darwin-amd64.sha256
    - release/terraform-provider-kafka-connect-linux-amd64
    - release/terraform-provider-kafka-connect-linux-amd64.sha256
  on:
    repo: wakeful/terraform-provider-kafka-connect
    branch: master
    tags: true
